version: '3'

services:
    ddns-server:
        build: .
        restart: always
        environment:
            DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
            CF_API_KEY: ${CF_API_KEY}
            DATABASE_URL: sqlite:///db.sqlite3
        volumes:
            - ./db.sqlite3:/app/db.sqlite3
            - static-files:/app/static

    nginx-proxy:
        image: nginx:1.18
        restart: always
        ports:
            - 8081:80
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
            - static-files:/var/www/html/static:ro
        depends_on:
            - app

volumes:
    static-files: