# Generated by Django 3.1.2 on 2020-10-29 06:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('key', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('domain', models.CharField(max_length=253)),
                ('cf_zone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6')], max_length=4)),
                ('remote_ip', models.GenericIPAddressField()),
                ('update_ip', models.GenericIPAddressField()),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.client')),
            ],
        ),
    ]
